### IMPORTS

In [1]:
# Imports that will be using in this notebook

from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Input
from tensorflow.keras import layers
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
import pickle

### READING IN DATA

In [2]:
# Data Source
# https://www.kaggle.com/kingburrito666/cannabis-strains

In [3]:
# Reading in cannabis data

weed = pd.read_csv('cannabis.csv')

In [4]:
# Checking the whole dataframe and making sure I read it in correctly

weed

Strain  ...                                        Description
0             100-Og  ...  $100 OG is a 50/50 hybrid strain that packs a ...
1     98-White-Widow  ...  The ‘98 Aloha White Widow is an especially pot...
2               1024  ...  1024 is a sativa-dominant hybrid bred in Spain...
3           13-Dawgs  ...  13 Dawgs is a hybrid of G13 and Chemdawg genet...
4           24K-Gold  ...  Also known as Kosher Tangie, 24k Gold is a 60%...
...              ...  ...                                                ...
2346         Zeus-Og  ...  Zeus OG is a hybrid cross between Pineapple OG...
2347        Zkittlez  ...  Zkittlez is an indica-dominant mix of Grape Ap...
2348     Zombie-Kush  ...  Zombie Kush by Ripper Seeds comes from two dif...
2349       Zombie-Og  ...  If you’re looking to transform into a flesh-ea...
2350        Zoom-Pie  ...  Zoom Pie (also known as Zombie Pie) is a heavy...

[2351 rows x 6 columns]

### DATA PREPROCESSING

In [5]:
# I know that there are some NaN values in the Flavor column so checking to see how many

weed[weed['Flavor'].isnull()]

Strain  ...                                        Description
103              Amethyst  ...  Amethyst is a hybrid cannabis strain from the ...
123          Arabian-Gold  ...  Arabian Gold is a heavy sativa strain of myste...
160          Bad-Azz-Kush  ...  Bad Azz Kush by Barney’s Farm was created with...
215             Birds-Eye  ...  Birds Eye is a variety of Jack Herer grown by ...
364              Boombaye  ...  Boombaye by Mr. Mack’s Snack is a CBD-rich str...
379          Broke-Diesel  ...  Broke Diesel is a 50/50 hybrid marijuana strai...
484         Chem-Jong-Ill  ...  This sativa-dominant cross is for cannabis pro...
574    Confidential-Wreck  ...  Confidential Wreck, also known as Lohan, is th...
673            Do-Over-Og  ...  Do-Over OG is an indica-dominant strain that c...
679                Domino  ...                                                NaN
770                 Ether  ...  Generally referred to as Alien Dawg (“Ether” c...
831               G-Force  ...  G-Force by Flying Dutchman is a hearty G13 and...
899              Goldwing  ...                                                NaN
964             Grimmdica  ...  Legendary Canadian breeders Brothers Grimm See...
970            Guido-Kush  ...                                                NaN
1066                 I-95  ...  I-95 is deep hybrid cut bred from Triangle Kus...
1093                 Jt15  ...  JT15 is an indica Kush cross with a powerful o...
1177                Khola  ...  Khola is a sociable cross between Brazilian, T...
1199             Krakatoa  ...                                                NaN
1252             Lem-Chem  ...  Lem Chem is a potent hybrid that is both sweet...
1365                Matsu  ...                                                NaN
1366              Mau-Mau  ...  Mau-Mau is a hybrid from Irie Vibe Seeds that ...
1440             Mud-Bite  ...  There is a very little known about Mud Bite. T...
1512    Old-Mother-Sativa  ...  Old Mother Sativa is an enormous plant with up...
1545       Orient-Express  ...  Orient Express by Ace Seeds is a sativa-domina...
1553               Pvc-Og  ...  PVC OG is a proprietary strain introduced by P...
1577       Peyton-Manning  ...  Peyton Manning is a horticultural homage to De...
1706       Purple-Pantera  ...  Purple Pantera is an indica-dominant hybrid br...
1711      Purple-Pinecone  ...  Purple Pinecone by Sagarmatha Seeds is a dense...
1756      Rebel-God-Smoke  ...  Rebel God Smoke is a pro-grade sativa-dominant...
1771           Redd-Cross  ...  Redd Cross is an indica-dominant hybrid bred b...
1772           Redding-Og  ...  Redding OG is a hybrid strain that won 3rd pla...
1853  Shining-Silver-Haze  ...  Shining Silver Haze is Royal Queen Seeds’ vers...
1916           Soul-Shine  ...  Soul Shine will put a smile on your face. Prov...
1965  South-Indian-Indica  ...  South Indian refers to the indigenous varietie...
1972           Space-Jill  ...  Space Jill by TGA Genetics is a recreation of ...
2091         Swiss-Sativa  ...  Swiss refers to any sativa strain that grows n...
2116       Tangie-Sunrise  ...  Tangie Sunrise by Palomar Craft Cannabis is li...
2130         Thaidal-Wave  ...  Thaidal Wave is a perfectly named hybrid that ...
2139             The-Fork  ...  Colorado Seed Inc.’s “The Fork” is dubbed as s...
2181          Transformer  ...  Transformer by Gage Green Genetics is a combin...
2225            Vanilluna  ...  World renowned Oregon breeder DJ Short used hi...
2237              Violeta  ...  Violeta by Ace Seeds is an indica-dominant hyb...
2248          Walrus-Kush  ...  While normally difficult to ignore, this Walru...
2257              Wembley  ...  Wembley by Pyramid Seeds is an indica-dominant...
2309         White-Walrus  ...  White Walrus is a phenotype of Chernobyl, grow...

[46 rows x 6 columns]

In [6]:
# Replacing the NaN values for none in the Flavor column

weed['Flavor'] = weed['Flavor'].replace(np.nan, 'none')

In [7]:
# Making sure that there are no NaN values left

weed[weed['Flavor'].isnull()]

Empty DataFrame
Columns: [Strain, Type, Rating, Effects, Flavor, Description]
Index: []

In [8]:
# Combining Effects and Flavor into once column to use for one hot encoding

weed['Effect_Flavor'] = weed['Effects'] + ',' +  weed['Flavor'] # If you don't add the comma it just smooshes the words together

In [9]:
# Checking to making sure it added correctly

weed

Strain  ...                                      Effect_Flavor
0             100-Og  ...  Creative,Energetic,Tingly,Euphoric,Relaxed,Ear...
1     98-White-Widow  ...  Relaxed,Aroused,Creative,Happy,Energetic,Flowe...
2               1024  ...  Uplifted,Happy,Relaxed,Energetic,Creative,Spic...
3           13-Dawgs  ...  Tingly,Creative,Hungry,Relaxed,Uplifted,Aprico...
4           24K-Gold  ...  Happy,Relaxed,Euphoric,Uplifted,Talkative,Citr...
...              ...  ...                                                ...
2346         Zeus-Og  ...  Happy,Uplifted,Relaxed,Euphoric,Energetic,Eart...
2347        Zkittlez  ...  Relaxed,Happy,Euphoric,Uplifted,Sleepy,Sweet,B...
2348     Zombie-Kush  ...  Relaxed,Sleepy,Talkative,Euphoric,Happy,Earthy...
2349       Zombie-Og  ...  Relaxed,Sleepy,Euphoric,Happy,Hungry,Sweet,Ear...
2350        Zoom-Pie  ...  Hungry,Relaxed,Uplifted,Happy,Sleepy,Berry,Ear...

[2351 rows x 7 columns]

In [10]:
# Checking one row to better see all the items and making sure the comma seperated the words correctly

weed['Effect_Flavor'][0]

'Creative,Energetic,Tingly,Euphoric,Relaxed,Earthy,Sweet,Citrus'

In [11]:
# Looking at my new column

weed['Effect_Flavor'].describe()

count          2351
unique         2257
top       None,None
freq             73
Name: Effect_Flavor, dtype: object

### MODEL PREPERATION

In [12]:
# Split into X and y

X = weed['Effect_Flavor']
y = weed['Strain']

In [13]:
# Checking X shape

X.shape

(2351,)

In [14]:
# Checking y shape

y.shape

(2351,)

In [15]:
# Since the neural network cannot take in straight text I am going to vectorize my X data

# create the transformer
vect = CountVectorizer()

# build vocab
vect.fit(X)

# transform text
dtm = vect.transform(X)

In [16]:
# Checking to see that the feature names are correct

print(vect.get_feature_names())

['ammonia', 'apple', 'apricot', 'aroused', 'berry', 'blue', 'blueberry', 'butter', 'cheese', 'chemical', 'chestnut', 'citrus', 'coffee', 'creative', 'diesel', 'dry', 'earthy', 'energetic', 'euphoric', 'flowery', 'focused', 'fruit', 'giggly', 'grape', 'grapefruit', 'happy', 'herbal', 'honey', 'hungry', 'lavender', 'lemon', 'lime', 'mango', 'menthol', 'mint', 'minty', 'mouth', 'none', 'nutty', 'orange', 'peach', 'pear', 'pepper', 'pine', 'pineapple', 'plum', 'pungent', 'relaxed', 'rose', 'sage', 'skunk', 'sleepy', 'spicy', 'strawberry', 'sweet', 'talkative', 'tar', 'tea', 'tingly', 'tobacco', 'tree', 'tropical', 'uplifted', 'vanilla', 'violet', 'woody']


In [17]:
# Now I am going to use todense() to turn X into a matrix

X = dtm.todense()

In [18]:
# Make sure it turned into a matrix correctly

X

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [19]:
# I am using label encoder for y
# Label encoder turns y into a numeric representation of the data

le = preprocessing.LabelEncoder()
y = le.fit_transform(y)

In [20]:
# Check to make sure that y is an array now

y

array([   0,   18,    1, ..., 2347, 2348, 2349])

In [21]:
# Checking to make sure the X shape looks good

X.shape

(2351, 66)

In [22]:
# Checking to make sure the y shape looks good

y.shape

(2351,)

In [23]:
# Checking to make sure my X and y look good

print(X[1])
print(y[0:5])

[[0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
[ 0 18  1  2  3]


### CREATE NEURAL NETWORK

In [24]:
# Creating my own optimizer
# AdamamsGrad is using a super low learning_rate which means the changes between epochs will be smaller

AdamamsGrad = tf.keras.optimizers.Adam(
    learning_rate=0.0001,
    amsgrad=False,
)

In [25]:
# Instantiating my model type and creating the model architecture

model = Sequential()

model.add(Input(66))
model.add(Dense(64, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(2350, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy',
              optimizer=AdamamsGrad, 
              metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                4288      
_________________________________________________________________
dense_1 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_2 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_3 (Dense)              (None, 2350)              603950    
Total params: 649,582
Trainable params: 649,582
Non-trainable params: 0
_________________________________________________________________


### TEST PREDICTION MODEL

In [26]:
# Fitting my model and getting my accuracy

model.fit(X,y, epochs=100)

Epoch 1/100
74/74 [==============================] - 0s 4ms/step - loss: 7.7792 - accuracy: 0.0000e+00
Epoch 2/100
74/74 [==============================] - 0s 4ms/step - loss: 7.7473 - accuracy: 0.0017
Epoch 3/100
74/74 [==============================] - 0s 4ms/step - loss: 7.7122 - accuracy: 0.0094
Epoch 4/100
74/74 [==============================] - 0s 4ms/step - loss: 7.6385 - accuracy: 0.0247
Epoch 5/100
74/74 [==============================] - 0s 4ms/step - loss: 7.5002 - accuracy: 0.0345
Epoch 6/100
74/74 [==============================] - 0s 4ms/step - loss: 7.2745 - accuracy: 0.0532
Epoch 7/100
74/74 [==============================] - 0s 4ms/step - loss: 6.9522 - accuracy: 0.0719
Epoch 8/100
74/74 [==============================] - 0s 4ms/step - loss: 6.5488 - accuracy: 0.1034
Epoch 9/100
74/74 [==============================] - 0s 4ms/step - loss: 6.0947 - accuracy: 0.1612
Epoch 10/100
74/74 [==============================] - 0s 4ms/step - loss: 5.6114 - accuracy: 0.2395
Epoch

### PICKLE THE MODEL